### ISSUE TITLE
"Get all live signed reports as public should succeed" test is flaky

### ISSUE THREAD

**Issue by joshlf** [covid19risk/covidwatch-cloud-functions#10]
The "Get all live signed reports as public should succeed" test sometimes fails and sometimes succeeds, implying that there is some accidental nondeterminism.

Concretely, when it fails, it fails with:

```text
Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (.../covidwatch-cloud-functions/functions/.mocha/test/integrated.test.js)
```

**Comment by inmyth** [comment]
Addressed at #21 . Basically test starts without waiting for build to finish first.
