### ISSUE TITLE
Document to install firebase tools using npm

### ISSUE THREAD

**Issue by joshlf** [covid19risk/covidwatch-cloud-functions#11]
The firebase installation docs recommend using a `curl|bash` approach for beginners. Unfortunately, the `firebase` tool that this installs can end up using a different version of NPM than the version of NPM used to build/run the project. In order to avoid this, it's better to install using `npm install -g firebase-tools`, which is another of the documented installation methods. We should make it clear in the README that this is the preferred method.

**Comment by madhavajay** [comment]
@joshlf Thanks for pointing that out I have fixed it here:
https://github.com/covid19risk/covidwatch-cloud-functions/commit/4c3fafe8361ee9ab157bfa402cb7ae455a307554

Let me know if you think this is sufficient.

**Comment by joshlf** [comment]
Looks good, thanks!
