### ISSUE TITLE
Add prettier & prettier config to the repo (and/or tsdx)

### ISSUE THREAD

**Issue by miridius** [covid19risk/covidwatch-cloud-functions#6]
Currently it seems that prettier is not included as a devDependency and there is no prettier config checked in. As a result there's no consistency in the file formatting - if I make a change to a file I'm getting the whole thing lighting up in the diff because the default prettier config is different to how the previous developer formatted the file.

What I would suggest as a way to solve this issue and simplify the whole build/lint/test process at the same time is that we could use tsdx to manage those tasks, because it handles both tsc and babel and ships with prettier included.

**Comment by miridius** [comment]
@madhavajay I could make a PR for this if you like, as I did the same setup recently on the tcn-node project.

One thing that would have to be agreed on is what prettier config to use. The defaults are printWidth 80, semicolons enabled, and double quotes over single quotes. I'm not really into those settings but I am in favour of sticking to defaults anyway just to avoid arguments.

**Comment by joshlf** [comment]
This is obsolete now that we've switched to Go.
